name: owl
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.8.1
  flutter_map:
  shared_preferences:
  flutter_map_line_editor:
  google_fonts:
  flutter_usb_serial:
  permission_handler:
  cached_network_image: ^3.3.0
  flutter_svg:
  flutter_map_dragmarker:
  flutter_popup:
  syncfusion_flutter_charts:
  cupertino_icons: ^1.0.2
  flutter_msp:
  flutter_libserialport:
  font_awesome_flutter:
  flutter_launcher_icons:
  flutter_native_splash:
  fl_chart:
  flutter_cube: ^0.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/Images/OWLogoApp.png"

flutter_native_splash:
  color: "#d1d4dc"
  image: Assets/Images/OWLogoi.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - Assets/3D/drone.obj
    - Assets/Images/polet.svg
    - Assets/Images/spirali.svg
    - Assets/Images/halfD.svg
    - Assets/Images/D1Dron4i.svg
    - Assets/Images/trash.svg
    - Assets/Images/Dron4iDevushka.svg
    - Assets/Images/Draf.svg
    - Assets/Images/Accum.svg
    - Assets/Images/Drone1.svg
    - Assets/Images/Config.svg
    - Assets/Images/orig.svg
    - Assets/Images/Port.svg
    - Assets/Images/Motor.svg
    - Assets/Images/above.png
    - Assets/Images/OWLogoApp.png
    - Assets/Images/Backowl.png



  fonts:
    - family: Josefine
      fonts:
        - asset: Assets/fonts/JSF.ttf
          weight: 700
        - asset: Assets/fonts/JSF-Italic.ttf
          style: italic

    - family: Lato
      fonts:
        - asset: Assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: Assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: Assets/fonts/Lato-Light.ttf
          weight: 300
