/// Auto-generated list of MSP command codes for Betaflight communication.
/// Based on Betaflight `MSPCodes` from JavaScript.

abstract class MspCodes {
  static const int MSP_API_VERSION = 1;
  static const int MSP_FC_VARIANT = 2;
  static const int MSP_FC_VERSION = 3;
  static const int MSP_BOARD_INFO = 4;
  static const int MSP_BUILD_INFO = 5;

  static const int MSP_NAME = 10; // DEPRECATED IN MSP 1.45
  static const int MSP_SET_NAME = 11; // DEPRECATED IN MSP 1.45

  static const int MSP_BATTERY_CONFIG = 32;
  static const int MSP_SET_BATTERY_CONFIG = 33;
  static const int MSP_MODE_RANGES = 34;
  static const int MSP_SET_MODE_RANGE = 35;
  static const int MSP_FEATURE_CONFIG = 36;
  static const int MSP_SET_FEATURE_CONFIG = 37;
  static const int MSP_BOARD_ALIGNMENT_CONFIG = 38;
  static const int MSP_SET_BOARD_ALIGNMENT_CONFIG = 39;
  static const int MSP_CURRENT_METER_CONFIG = 40;
  static const int MSP_SET_CURRENT_METER_CONFIG = 41;
  static const int MSP_MIXER_CONFIG = 42;
  static const int MSP_SET_MIXER_CONFIG = 43;
  static const int MSP_RX_CONFIG = 44;
  static const int MSP_SET_RX_CONFIG = 45;
  static const int MSP_LED_COLORS = 46;
  static const int MSP_SET_LED_COLORS = 47;
  static const int MSP_LED_STRIP_CONFIG = 48;
  static const int MSP_SET_LED_STRIP_CONFIG = 49;
  static const int MSP_RSSI_CONFIG = 50;
  static const int MSP_SET_RSSI_CONFIG = 51;
  static const int MSP_ADJUSTMENT_RANGES = 52;
  static const int MSP_SET_ADJUSTMENT_RANGE = 53;
  static const int MSP_CF_SERIAL_CONFIG = 54;
  static const int MSP_SET_CF_SERIAL_CONFIG = 55;
  static const int MSP_VOLTAGE_METER_CONFIG = 56;
  static const int MSP_SET_VOLTAGE_METER_CONFIG = 57;
  static const int MSP_SONAR = 58; // in firmware named as MSP_SONAR_ALTITUDE
  static const int MSP_PID_CONTROLLER = 59;
  static const int MSP_SET_PID_CONTROLLER = 60;
  static const int MSP_ARMING_CONFIG = 61;
  static const int MSP_SET_ARMING_CONFIG = 62;
  static const int MSP_RX_MAP = 64;
  static const int MSP_SET_RX_MAP = 65;
  static const int MSP_BF_CONFIG = 66; // DEPRECATED
  static const int MSP_SET_BF_CONFIG = 67; // DEPRECATED
  static const int MSP_SET_REBOOT = 68;
  static const int MSP_BF_BUILD_INFO = 69; // Not used
  static const int MSP_DATAFLASH_SUMMARY = 70;
  static const int MSP_DATAFLASH_READ = 71;
  static const int MSP_DATAFLASH_ERASE = 72;
  static const int MSP_LOOP_TIME = 73;
  static const int MSP_SET_LOOP_TIME = 74;
  static const int MSP_FAILSAFE_CONFIG = 75;
  static const int MSP_SET_FAILSAFE_CONFIG = 76;
  static const int MSP_RXFAIL_CONFIG = 77;
  static const int MSP_SET_RXFAIL_CONFIG = 78;
  static const int MSP_SDCARD_SUMMARY = 79;
  static const int MSP_BLACKBOX_CONFIG = 80;
  static const int MSP_SET_BLACKBOX_CONFIG = 81;
  static const int MSP_TRANSPONDER_CONFIG = 82;
  static const int MSP_SET_TRANSPONDER_CONFIG = 83;
  static const int MSP_OSD_CONFIG = 84;
  static const int MSP_SET_OSD_CONFIG = 85;
  static const int MSP_OSD_CHAR_READ = 86;
  static const int MSP_OSD_CHAR_WRITE = 87;
  static const int MSP_VTX_CONFIG = 88;
  static const int MSP_SET_VTX_CONFIG = 89;
  static const int MSP_ADVANCED_CONFIG = 90;
  static const int MSP_SET_ADVANCED_CONFIG = 91;
  static const int MSP_FILTER_CONFIG = 92;
  static const int MSP_SET_FILTER_CONFIG = 93;
  static const int MSP_PID_ADVANCED = 94;
  static const int MSP_SET_PID_ADVANCED = 95;
  static const int MSP_SENSOR_CONFIG = 96;
  static const int MSP_SET_SENSOR_CONFIG = 97;
  static const int MSP_ARMing_DISABLE = 99;
  static const int MSP_STATUS = 101;
  static const int MSP_RAW_IMU = 102;
  static const int MSP_SERVO = 103;
  static const int MSP_MOTOR = 104;
  static const int MSP_RC = 105;
  static const int MSP_RAW_GPS = 106;
  static const int MSP_COMP_GPS = 107;
  static const int MSP_ATTITUDE = 108;
  static const int MSP_ALTITUDE = 109;
  static const int MSP_ANALOG = 110;
  static const int MSP_RC_TUNING = 111;
  static const int MSP_PID = 112;
  static const int MSP_BOXNAMES = 116;
  static const int MSP_PIDNAMES = 117;
  static const int MSP_BOXIDS = 119;
  static const int MSP_SERVO_CONFIGURATIONS = 120;
  static const int MSP_MOTOR_3D_CONFIG = 124;
  static const int MSP_RC_DEADBAND = 125;
  static const int MSP_SENSOR_ALIGNMENT = 126;
  static const int MSP_LED_STRIP_MODECOLOR = 127;
  static const int MSP_VOLTAGE_METERS = 128;
  static const int MSP_CURRENT_METERS = 129;
  static const int MSP_BATTERY_STATE = 130;
  static const int MSP_MOTOR_CONFIG = 131;
  static const int MSP_GPS_CONFIG = 132;
  static const int MSP_COMPASS_CONFIG = 133;
  static const int MSP_GPS_RESCUE = 135;
  static const int MSP_VTXTABLE_BAND = 137;
  static const int MSP_VTXTABLE_POWERLEVEL = 138;
  static const int MSP_MOTOR_TELEMETRY = 139;
  static const int MSP_SIMPLIFIED_TUNING = 140;
  static const int MSP_SET_SIMPLIFIED_TUNING = 141;
  static const int MSP_CALCULATE_SIMPLIFIED_PID = 142;
  static const int MSP_CALCULATE_SIMPLIFIED_GYRO = 143;
  static const int MSP_CALCULATE_SIMPLIFIED_DTERM = 144;
  static const int MSP_VALIDATE_SIMPLIFIED_TUNING = 145;
  static const int MSP_STATUS_EX = 150;
  static const int MSP_UID = 160;
  static const int MSP_GPS_SV_INFO = 164;
  static const int MSP_DISPLAYPORT = 182;
  static const int MSP_COPY_PROFILE = 183;
  static const int MSP_BEEPER_CONFIG = 184;
  static const int MSP_SET_BEEPER_CONFIG = 185;
  static const int MSP_SET_OSD_CANVAS = 188;
  static const int MSP_OSD_CANVAS = 189;
  static const int MSP_SET_RAW_RC = 200;
  static const int MSP_SET_PID = 202;
  static const int MSP_SET_RC_TUNING = 204;
  static const int MSP_ACC_CALIBRATION = 205;
  static const int MSP_MAG_CALIBRATION = 206;
  static const int MSP_RESET_CONF = 208;
  static const int MSP_SELECT_SETTING = 210;
  static const int MSP_SET_SERVO_CONFIGURATION = 212;
  static const int MSP_SET_MOTOR = 214;
  static const int MSP_SET_MOTOR_3D_CONFIG = 217;
  static const int MSP_SET_RC_DEADBAND = 218;
  static const int MSP_SET_RESET_CURR_PID = 219;
  static const int MSP_SET_SENSOR_ALIGNMENT = 220;
  static const int MSP_SET_LED_STRIP_MODECOLOR = 221;
  static const int MSP_SET_MOTOR_CONFIG = 222;
  static const int MSP_SET_GPS_CONFIG = 223;
  static const int MSP_SET_COMPASS_CONFIG = 224;
  static const int MSP_SET_GPS_RESCUE = 225;
  static const int MSP_SET_VTXTABLE_BAND = 227;
  static const int MSP_SET_VTXTABLE_POWERLEVEL = 228;
  static const int MSP_MULTIPLE_MSP = 230;
  static const int MSP_MODE_RANGES_EXTRA = 238;
  static const int MSP_SET_ACC_TRIM = 239;
  static const int MSP_ACC_TRIM = 240;
  static const int MSP_SERVO_MIX_RULES = 241;
  static const int MSP_SET_SERVO_MIX_RULE = 242;
  static const int MSP_SET_RTC = 246;
  static const int MSP_RTC = 247;
  static const int MSP_SET_SIGNATURE = 249;
  static const int MSP_EEPROM_WRITE = 250;
  static const int MSP_DEBUGMSG = 253;
  static const int MSP_DEBUG = 254;

  // MSPv2 Common
  static const int MSP2_COMMON_SERIAL_CONFIG = 0x1009;
  static const int MSP2_COMMON_SET_SERIAL_CONFIG = 0x100A;

  // MSPv2 Betaflight specific
  static const int MSP2_BETAFLIGHT_BIND = 0x3000;
  static const int MSP2_MOTOR_OUTPUT_REORDERING = 0x3001;
  static const int MSP2_SET_MOTOR_OUTPUT_REORDERING = 0x3002;
  static const int MSP2_SEND_DSHOT_COMMAND = 0x3003;
  static const int MSP2_GET_VTX_DEVICE_STATUS = 0x3004;
  static const int MSP2_GET_OSD_WARNINGS = 0x3005;
  static const int MSP2_GET_TEXT = 0x3006;
  static const int MSP2_SET_TEXT = 0x3007;
  static const int MSP2_GET_LED_STRIP_CONFIG_VALUES = 0x3008;
  static const int MSP2_SET_LED_STRIP_CONFIG_VALUES = 0x3009;
  static const int MSP2_SENSOR_CONFIG_ACTIVE = 0x300A;
  static const int MSP2_MCU_INFO = 0x300C;

  // MSP2 GET/SET TEXT variable types
  static const int PILOT_NAME = 1;
  static const int CRAFT_NAME = 2;
  static const int PID_PROFILE_NAME = 3;
  static const int RATE_PROFILE_NAME = 4;
  static const int BUILD_KEY = 5;
}
